apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubank-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: ubank/chatbot:latest
        ports:
        - containerPort: 5000
        env:
        - name: WATSON_API_KEY
          valueFrom:
            secretKeyRef:
              name: watson-secret
              key: api_key